# Generated by Django 5.1.4 on 2026-07-22 12:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0004_long_term_snapshots_ged_quota"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportingSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("TENANT", "Filiale"), ("GROUP", "Groupe")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        db_index=True,
                        default="dashboard",
                        help_text="dashboard | breakdown:<dimension>",
                        max_length=64,
                        verbose_name="type",
                    ),
                ),
                (
                    "params_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hash des filtres (vide = sans filtre).",
                        max_length=64,
                        verbose_name="empreinte filtres",
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_snapshots",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "snapshot reporting",
                "verbose_name_plural": "snapshots reporting",
                "indexes": [
                    models.Index(
                        fields=["scope", "kind", "-computed_at"],
                        name="reporting_r_scope_947ad7_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "tenant", "kind", "params_hash"),
                        name="uniq_reporting_snapshot",
                    )
                ],
            },
        ),
    ]
