# Generated by Django 5.1.4 on 2026-09-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_collection_reminder_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantnotificationsettings',
            name='from_email',
            field=models.CharField(blank=True, help_text="Adresse seule (ex. noreply@filiale.com). Si vide, utilise l'identifiant SMTP. L'affichage est toujours « NOREPLY {filiale} <adresse> », sauf si vous saisissez déjà un nom complet « Nom <adresse> ».", max_length=255, verbose_name='expéditeur (From)'),
        ),
        migrations.AlterField(
            model_name='tenantnotificationsettings',
            name='notify_on_completion',
            field=models.BooleanField(default=True, help_text="Lorsque le circuit est approuvé : e-mail à l'initiateur du dossier (et aux intervenants) pour l'informer que le dossier est validé et qu'il peut générer les contrats à faire signer. Couvre aussi les autres fins de circuit selon les options ci-dessous.", verbose_name='informer en fin de circuit (approbation)'),
        ),
        migrations.AlterField(
            model_name='tenantnotificationsettings',
            name='notify_on_rejection',
            field=models.BooleanField(default=True, help_text="Envoie un e-mail à l'initiateur du dossier (et aux intervenants) lorsque le circuit est rejeté.", verbose_name="informer l'initiateur en cas de rejet"),
        ),
        migrations.AlterField(
            model_name='tenantnotificationsettings',
            name='notify_on_return',
            field=models.BooleanField(default=True, help_text="Envoie un e-mail à l'initiateur du dossier (et aux intervenants) lorsque le dossier est renvoyé pour correction.", verbose_name="informer l'initiateur en cas de renvoi"),
        ),
    ]
