# Generated by Django 5.1.4 on 2026-07-10 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPromise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='montant promis')),
                ('promised_date', models.DateField(verbose_name='date promise')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('KEPT', 'Tenue'), ('BROKEN', 'Non tenue')], default='PENDING', max_length=10)),
            ],
            options={
                'verbose_name': 'promesse de paiement',
                'verbose_name_plural': 'promesses de paiement',
                'ordering': ['-promised_date'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='montant')),
                ('payment_date', models.DateField(verbose_name='date de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
            ],
            options={
                'verbose_name': 'encaissement',
                'verbose_name_plural': 'encaissements',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='CollectionAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('action_type', models.CharField(choices=[('CALL', 'Appel téléphonique'), ('SMS', 'SMS'), ('EMAIL', 'Courriel'), ('LETTER', 'Courrier'), ('VISIT', 'Visite terrain'), ('LEGAL', 'Acte judiciaire')], max_length=10)),
                ('action_date', models.DateField(verbose_name='date')),
                ('result', models.CharField(blank=True, max_length=255, verbose_name='résultat')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'action de recouvrement',
                'verbose_name_plural': 'actions de recouvrement',
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='CollectionCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('stage', models.CharField(choices=[('AMICABLE', 'Amiable'), ('PRECONTENTIOUS', 'Précontentieux'), ('LITIGATION', 'Contentieux'), ('CLOSED', 'Clôturé')], db_index=True, default='AMICABLE', max_length=20)),
                ('par_class', models.CharField(choices=[('PAR0', 'Sain'), ('PAR1_30', 'PAR 1-30'), ('PAR31_90', 'PAR 31-90'), ('PAR91_180', 'PAR 91-180'), ('PAR180_PLUS', 'PAR > 180')], db_index=True, default='PAR0', max_length=20)),
                ('days_overdue', models.PositiveIntegerField(default=0, verbose_name='jours de retard')),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='montant en retard')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_cases', to=settings.AUTH_USER_MODEL, verbose_name='agent de recouvrement')),
            ],
            options={
                'verbose_name': 'dossier de recouvrement',
                'verbose_name_plural': 'dossiers de recouvrement',
                'ordering': ['-days_overdue'],
            },
        ),
    ]
