# Generated by Django 5.1.4 on 2026-07-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
        ('credits', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncase',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_case', to='credits.loan', verbose_name='prêt'),
        ),
        migrations.AddField(
            model_name='collectioncase',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale'),
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='collections.collectioncase', verbose_name='dossier'),
        ),
        migrations.AddField(
            model_name='paymentpromise',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='collections.collectioncase', verbose_name='dossier'),
        ),
        migrations.AddField(
            model_name='paymentpromise',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='credits.loan', verbose_name='prêt'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale'),
        ),
        migrations.AddIndex(
            model_name='collectioncase',
            index=models.Index(fields=['tenant', 'par_class', 'stage'], name='collections_tenant__ba6d33_idx'),
        ),
    ]
