# Generated by Django 5.1.4 on 2026-09-07 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0006_rename_next_action_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='litigationfile',
            options={'ordering': ['-hearing_date', '-created_at'], 'verbose_name': 'dossier contentieux', 'verbose_name_plural': 'dossiers contentieux'},
        ),
        migrations.RenameIndex(
            model_name='legalparty',
            new_name='collections_tenant__f109b5_idx',
            old_name='collections_legal_party_idx',
        ),
        migrations.RenameIndex(
            model_name='litigationfile',
            new_name='collections_tenant__74d461_idx',
            old_name='collections_lit_status_hear_idx',
        ),
        migrations.AlterField(
            model_name='litigationfile',
            name='case_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='référence judiciaire / RG'),
        ),
        migrations.AlterField(
            model_name='litigationfile',
            name='law_firm',
            field=models.ForeignKey(blank=True, limit_choices_to={'party_type': 'LAW_FIRM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litigations_as_firm', to='collections.legalparty', verbose_name='cabinet mandaté'),
        ),
    ]
