# Generated by Django 5.1.4 on 2026-09-10 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0010_action_authorship_dialogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiondialoguemessage',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_messages', to='collections.collectionaction', verbose_name='action'),
        ),
    ]
