# Generated by Django 5.1.4 on 2026-07-10 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surety',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('surety_type', models.CharField(choices=[('PHYSICAL', 'Personne physique'), ('MORAL', 'Personne morale')], max_length=20)),
                ('name', models.CharField(max_length=255, verbose_name='nom / raison sociale')),
                ('identifier', models.CharField(blank=True, max_length=100, verbose_name='pièce / RCCM')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('commitment_ceiling', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="plafond d'engagement")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'caution',
                'verbose_name_plural': 'cautions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SuretyEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='montant engagé')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='date de signature')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('RELEASED', 'Libéré'), ('CALLED', 'Appelé')], default='ACTIVE', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surety_engagements', to='credits.creditapplication', verbose_name='dossier')),
                ('surety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='sureties.surety', verbose_name='caution')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'engagement de caution',
                'verbose_name_plural': 'engagements de caution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='surety',
            index=models.Index(fields=['tenant', 'name'], name='sureties_su_tenant__ac233a_idx'),
        ),
    ]
