# Generated by Django 5.1.4 on 2026-07-13 15:20

import apps.sureties.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sureties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surety',
            options={'ordering': ['-created_at'], 'verbose_name': 'caution', 'verbose_name_plural': 'cautions'},
        ),
        migrations.AddField(
            model_name='surety',
            name='activity',
            field=models.CharField(blank=True, max_length=200, verbose_name='activité de la caution'),
        ),
        migrations.AddField(
            model_name='surety',
            name='birth_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='pays de naissance'),
        ),
        migrations.AddField(
            model_name='surety',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AddField(
            model_name='surety',
            name='estimated_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='estimation de revenu'),
        ),
        migrations.AddField(
            model_name='surety',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='prénom'),
        ),
        migrations.AddField(
            model_name='surety',
            name='id_document_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'expiration de la pièce"),
        ),
        migrations.AddField(
            model_name='surety',
            name='id_document_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'établissement de la pièce"),
        ),
        migrations.AddField(
            model_name='surety',
            name='id_document_scan',
            field=models.FileField(blank=True, upload_to=apps.sureties.models.surety_file_path, verbose_name="scan de la pièce d'identité"),
        ),
        migrations.AddField(
            model_name='surety',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('PASSPORT', 'Passeport'), ('CNI', "Carte nationale d'identité"), ('DRIVING_LICENSE', 'Permis de conduire'), ('CONSULAR_CARD', 'Carte consulaire')], max_length=20, verbose_name="type de pièce d'identité"),
        ),
        migrations.AddField(
            model_name='surety',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='surety',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name="n° de la pièce d'identité"),
        ),
        migrations.AddField(
            model_name='surety',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.sureties.models.surety_file_path, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='surety',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='nom / raison sociale'),
        ),
        migrations.AlterField(
            model_name='surety',
            name='surety_type',
            field=models.CharField(choices=[('PHYSICAL', 'Personne physique'), ('MORAL', 'Personne morale')], default='PHYSICAL', max_length=20),
        ),
        migrations.CreateModel(
            name='SuretyPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('number', models.CharField(max_length=50, verbose_name='numéro')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='libellé')),
                ('surety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='sureties.surety', verbose_name='caution')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'téléphone caution',
                'verbose_name_plural': 'téléphones caution',
                'ordering': ['created_at'],
            },
        ),
    ]
