# Generated by Django 5.1.4 on 2026-07-14 15:28

import apps.sureties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sureties', '0002_alter_surety_options_surety_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surety',
            name='id_document_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.sureties.models.surety_file_path, verbose_name="scan de la pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='surety',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to=apps.sureties.models.surety_file_path, verbose_name='photo'),
        ),
    ]
