# Generated by Django 5.1.4 on 2026-09-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sureties', '0007_suretyengagement_enrichment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surety',
            name='manager_id_document_type',
            field=models.CharField(blank=True, choices=[('PASSPORT', 'Passeport'), ('CNI', "Carte nationale d'identité"), ('DRIVING_LICENSE', 'Permis de conduire'), ('CONSULAR_CARD', 'Carte consulaire')], max_length=20, verbose_name='type de pièce du gérant'),
        ),
    ]
