# Generated by Django 5.1.4 on 2026-07-10 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('WORKFLOW', 'Action workflow'), ('INTEGRATION', 'Échange Core Banking')], max_length=20)),
                ('model_label', models.CharField(blank=True, max_length=120, verbose_name='entité')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='id objet')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='libellé objet')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='changements')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "entrée d'audit",
                'verbose_name_plural': "piste d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_label', 'object_id'], name='audit_audit_model_l_b619eb_idx'), models.Index(fields=['tenant', '-timestamp'], name='audit_audit_tenant__1b7744_idx')],
            },
        ),
    ]
