# Generated by Django 5.1.4 on 2026-07-10 10:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('label', models.CharField(max_length=255, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('client_type', models.CharField(choices=[('INDIVIDUAL', 'Particulier'), ('PROFESSIONAL', 'Professionnel'), ('CORPORATE', 'Entreprise'), ('ALL', 'Tous')], default='ALL', max_length=20)),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('amount_min', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant minimum')),
                ('amount_max', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant maximum')),
                ('duration_min_months', models.PositiveIntegerField(default=1, verbose_name='durée min (mois)')),
                ('duration_max_months', models.PositiveIntegerField(default=60, verbose_name='durée max (mois)')),
                ('interest_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name="taux d'intérêt annuel (%)")),
                ('processing_fee_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='frais de dossier (%)')),
                ('requires_guarantee', models.BooleanField(default=False, verbose_name='garantie obligatoire')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'produit de crédit',
                'verbose_name_plural': 'produits de crédit',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('label', models.CharField(max_length=255, verbose_name='libellé')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='obligatoire')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='catalog.creditproduct', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'pièce de check-list',
                'verbose_name_plural': 'check-list documentaire',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('label', models.CharField(max_length=255, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'famille de produits',
                'verbose_name_plural': 'familles de produits',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='creditproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory', verbose_name='famille'),
        ),
        migrations.CreateModel(
            name='RejectReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('label', models.CharField(max_length=255, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'motif de rejet',
                'verbose_name_plural': 'motifs de rejet',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_productcategory_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='creditproduct',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_creditproduct_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='rejectreason',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_rejectreason_code_per_tenant'),
        ),
    ]
