# Generated by Django 5.1.4 on 2026-09-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditproduct',
            name='cbs_product_code',
            field=models.CharField(blank=True, help_text='Identifiant Perfect / CBS du produit de crédit.', max_length=64, verbose_name='code produit crédit CBS (idProduitCrd)'),
        ),
        migrations.AddField(
            model_name='creditproduct',
            name='cbs_repayment_product_code',
            field=models.CharField(blank=True, help_text='Identifiant Perfect / CBS du produit de remboursement (ex. compte courant).', max_length=64, verbose_name='code produit remboursement CBS (idProduitRemb)'),
        ),
    ]
