# Generated by Django 5.1.4 on 2026-09-04 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cbs_disbursement_fields'),
        ('tenants', '0005_cbs_disbursement_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('label', models.CharField(max_length=255, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('cbs_code', models.CharField(blank=True, help_text="Code Perfect / CBS envoyé lors des appels d'intégration.", max_length=64, verbose_name='identifiant CBS')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'devise',
                'verbose_name_plural': 'devises',
                'ordering': ['sort_order', 'label'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='unique_currency_code_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='LoanPeriodicity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('label', models.CharField(max_length=255, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('cbs_code', models.CharField(blank=True, help_text="Code Perfect / CBS envoyé lors des appels d'intégration.", max_length=64, verbose_name='identifiant CBS')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('periods_per_year', models.PositiveIntegerField(default=12, help_text="Utilisé pour calculer le nombre d'échéances.", verbose_name='périodes / an')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'périodicité',
                'verbose_name_plural': 'périodicités',
                'ordering': ['sort_order', 'label'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='unique_loanperiodicity_code_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='RepaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('label', models.CharField(max_length=255, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('cbs_code', models.CharField(blank=True, help_text="Code Perfect / CBS envoyé lors des appels d'intégration.", max_length=64, verbose_name='identifiant CBS')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'méthode de remboursement',
                'verbose_name_plural': 'méthodes de remboursement',
                'ordering': ['sort_order', 'label'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='unique_repaymentmethod_code_per_tenant')],
            },
        ),
    ]
