# Generated by Django 5.1.4 on 2026-07-10 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('target_type', models.CharField(choices=[('CREDIT', 'Dossier de crédit')], default='CREDIT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': "circuit d'approbation",
                'verbose_name_plural': "circuits d'approbation",
                'ordering': ['code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=255, verbose_name="nom de l'étape")),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ordre')),
                ('mode', models.CharField(choices=[('SEQUENTIAL', 'Séquentielle'), ('PARALLEL', 'Parallèle')], default='SEQUENTIAL', max_length=20)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='montant plancher')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='montant plafond')),
                ('min_risk_level', models.PositiveIntegerField(blank=True, null=True, verbose_name='niveau de risque minimal')),
                ('sla_hours', models.PositiveIntegerField(default=48, verbose_name='SLA (heures)')),
                ('allow_return', models.BooleanField(default=True, verbose_name='autorise le retour')),
                ('required_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='auth.group', verbose_name='rôle habilité')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflowdefinition', verbose_name='circuit')),
            ],
            options={
                'verbose_name': "étape d'approbation",
                'verbose_name_plural': "étapes d'approbation",
                'ordering': ['definition', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('object_id', models.UUIDField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('RETURNED', 'Retourné pour correction')], default='IN_PROGRESS', max_length=20)),
                ('current_order', models.PositiveIntegerField(default=0, verbose_name='étape courante')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('risk_level', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowdefinition', verbose_name='circuit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'instance de workflow',
                'verbose_name_plural': 'instances de workflow',
            },
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('RETURNED', 'Retournée'), ('SKIPPED', 'Ignorée')], default='PENDING', max_length=20)),
                ('decision_comment', models.TextField(blank=True, verbose_name='commentaire de décision')),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='échéance SLA')),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tasks', to=settings.AUTH_USER_MODEL)),
                ('reject_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tasks', to='catalog.rejectreason')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workflow.approvalstep', verbose_name='étape')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.workflowinstance', verbose_name='instance')),
            ],
            options={
                'verbose_name': "tâche d'approbation",
                'verbose_name_plural': "tâches d'approbation",
                'ordering': ['step__order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowdefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'code', 'version'), name='unique_workflow_code_version_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='workflow_wo_content_5cb705_idx'),
        ),
    ]
