# Generated by Django 5.1.4 on 2026-07-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinstance',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('RETURNED', 'Retourné pour correction'), ('CANCELLED', 'Annulé')], default='IN_PROGRESS', max_length=20),
        ),
    ]
