# Generated by Django 5.1.4 on 2026-07-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_workflowinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltask',
            name='proposed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='montant proposé à cette étape'),
        ),
    ]
