# Generated by Django 5.1.4 on 2026-07-16 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_branding'),
        ('workflow', '0004_opinion_step_kind_approvalcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalcondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='approvalcondition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='approvalcondition',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale'),
        ),
        migrations.AlterField(
            model_name='approvalcondition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
    ]
