# Generated by Django 5.1.4 on 2026-09-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_target_type_main_levee_dation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowdefinition',
            name='target_type',
            field=models.CharField(choices=[('CREDIT', 'Dossier de crédit'), ('MAIN_LEVEE', 'Main levée'), ('DATION', 'Dation en paiement'), ('FORMALISATION', 'Formalisation de garantie')], default='CREDIT', max_length=20),
        ),
    ]
