# Generated by Django 5.1.4 on 2026-09-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_client_type_groupement'),
        ('workflow', '0007_alter_workflowdefinition_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdefinition',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Inclusif. Vide = pas de plafond.', max_digits=18, null=True, verbose_name='montant plafond (circuit)'),
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Inclusif. Vide = pas de plancher.', max_digits=18, null=True, verbose_name='montant plancher (circuit)'),
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Circuit réservé à ce produit. Vide = tous les produits (sauf filtre famille).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_definitions', to='catalog.creditproduct', verbose_name='produit de crédit'),
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='product_category',
            field=models.ForeignKey(blank=True, help_text='Circuit réservé à cette famille (ex. immobilier). Ignoré si un produit précis est renseigné.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_definitions', to='catalog.productcategory', verbose_name='famille de produits'),
        ),
    ]
