# Generated by Django 5.1.4 on 2026-07-10 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreBankingConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('protocol', models.CharField(choices=[('REST', 'API REST'), ('SOAP', 'Service SOAP'), ('SFTP', 'Échange SFTP'), ('BATCH', 'Fichier batch')], max_length=10)),
                ('base_url', models.CharField(blank=True, max_length=500, verbose_name="URL d'accès")),
                ('auth_config', models.JSONField(blank=True, default=dict, verbose_name='authentification')),
                ('mapping_rules', models.JSONField(blank=True, default=dict, verbose_name='règles de mapping')),
                ('certificate_reference', models.CharField(blank=True, max_length=255, verbose_name='réf. certificat')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, verbose_name='timeout (s)')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='tentatives max')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'connecteur Core Banking',
                'verbose_name_plural': 'connecteurs Core Banking',
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('operation', models.CharField(max_length=100, verbose_name='opération')),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Sortant'), ('INBOUND', 'Entrant')], default='OUTBOUND', max_length=10)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('RETRY', 'À rejouer')], db_index=True, default='PENDING', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='tentatives')),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='réf. externe (CBS)')),
                ('error_message', models.TextField(blank=True, verbose_name="message d'erreur")),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='corebanking.corebankingconnector', verbose_name='connecteur')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': "journal d'intégration",
                'verbose_name_plural': "journaux d'intégration",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='corebankingconnector',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_connector_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='integrationlog',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('connector', 'idempotency_key'), name='unique_idempotency_per_connector'),
        ),
    ]
