# Generated by Django 5.1.4 on 2026-07-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_agencies_data_scope'),
        ('tenants', '0002_tenant_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agencies',
            field=models.ManyToManyField(blank=True, help_text="Agences auxquelles l'utilisateur a accès.", related_name='members', to='tenants.agency', verbose_name='agences'),
        ),
    ]
