# Generated by Django 5.1.4 on 2026-07-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_agencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_secret",
            field=models.CharField(
                blank=True,
                help_text="Secret base32 pour l'authentification TOTP (vide si MFA inactif).",
                max_length=64,
                verbose_name="secret TOTP",
            ),
        ),
    ]
