# Generated by Django 5.1.4 on 2026-09-04 15:40

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_must_change_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cbs_id',
            field=models.CharField(blank=True, help_text='Identifiant Perfect / CBS du gestionnaire (optionnel).', max_length=64, verbose_name='identifiant CBS (idGestionnaire)'),
        ),
    ]
