# Generated by Django 5.1.4 on 2026-07-10 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(blank=True, max_length=30, verbose_name='référence client')),
                ('client_type', models.CharField(choices=[('INDIVIDUAL', 'Particulier'), ('PROFESSIONAL', 'Professionnel'), ('CORPORATE', 'Entreprise')], max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='nom')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name="pièce d'identité (n°)")),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='raison sociale')),
                ('legal_form', models.CharField(blank=True, max_length=100, verbose_name='forme juridique')),
                ('rccm', models.CharField(blank=True, max_length=50, verbose_name='RCCM')),
                ('ifu', models.CharField(blank=True, max_length=50, verbose_name='IFU')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('kyc_status', models.CharField(choices=[('PENDING', 'À vérifier'), ('VALIDATED', 'Validé'), ('REJECTED', 'Rejeté'), ('EXPIRED', 'Expiré')], default='PENDING', max_length=20, verbose_name='statut KYC')),
                ('kyc_validated_at', models.DateField(blank=True, null=True, verbose_name='KYC validé le')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='tenants.agency', verbose_name='agence')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'client_type'], name='clients_cli_tenant__80f848_idx'), models.Index(fields=['reference'], name='clients_cli_referen_3d6684_idx')],
            },
        ),
    ]
