# Generated by Django 5.1.4 on 2026-07-10 13:48

import apps.clients.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='pays de naissance'),
        ),
        migrations.AddField(
            model_name='client',
            name='civility',
            field=models.CharField(blank=True, choices=[('MR', 'Monsieur'), ('MRS', 'Madame'), ('MISS', 'Mademoiselle')], max_length=10, verbose_name='civilité'),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='pays'),
        ),
        migrations.AddField(
            model_name='client',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nom et prénom du père'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_document_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'expiration de la pièce"),
        ),
        migrations.AddField(
            model_name='client',
            name='id_document_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'établissement de la pièce"),
        ),
        migrations.AddField(
            model_name='client',
            name='id_document_scan',
            field=models.FileField(blank=True, upload_to=apps.clients.models.client_file_path, verbose_name="scan de la pièce d'identité"),
        ),
        migrations.AddField(
            model_name='client',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('PASSPORT', 'Passeport'), ('CNI', "Carte nationale d'identité"), ('DRIVING_LICENSE', 'Permis de conduire'), ('CONSULAR_CARD', 'Carte consulaire')], max_length=20, verbose_name="type de pièce d'identité"),
        ),
        migrations.AddField(
            model_name='client',
            name='ifu_scan',
            field=models.FileField(blank=True, upload_to=apps.clients.models.client_file_path, verbose_name='scan IFU'),
        ),
        migrations.AddField(
            model_name='client',
            name='manager_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='adresse du gérant'),
        ),
        migrations.AddField(
            model_name='client',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email du gérant'),
        ),
        migrations.AddField(
            model_name='client',
            name='manager_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='prénom du gérant'),
        ),
        migrations.AddField(
            model_name='client',
            name='manager_id_document_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='n° de pièce du gérant'),
        ),
        migrations.AddField(
            model_name='client',
            name='manager_id_document_scan',
            field=models.FileField(blank=True, upload_to=apps.clients.models.client_file_path, verbose_name='scan pièce du gérant'),
        ),
        migrations.AddField(
            model_name='client',
            name='manager_id_document_type',
            field=models.CharField(blank=True, choices=[('PASSPORT', 'Passeport'), ('CNI', "Carte nationale d'identité"), ('DRIVING_LICENSE', 'Permis de conduire'), ('CONSULAR_CARD', 'Carte consulaire')], max_length=20, verbose_name='type de pièce du gérant'),
        ),
        migrations.AddField(
            model_name='client',
            name='manager_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nom du gérant'),
        ),
        migrations.AddField(
            model_name='client',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='téléphone du gérant'),
        ),
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Célibataire'), ('MARRIED', 'Marié(e)'), ('DIVORCED', 'Divorcé(e)'), ('WIDOWED', 'Veuf/Veuve')], max_length=15, verbose_name='situation matrimoniale'),
        ),
        migrations.AddField(
            model_name='client',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nom et prénom de la mère'),
        ),
        migrations.AddField(
            model_name='client',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='nationalité'),
        ),
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.clients.models.client_file_path, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='client',
            name='profession',
            field=models.CharField(blank=True, max_length=150, verbose_name='profession'),
        ),
        migrations.AddField(
            model_name='client',
            name='rccm_scan',
            field=models.FileField(blank=True, upload_to=apps.clients.models.client_file_path, verbose_name='scan RCCM'),
        ),
        migrations.AddField(
            model_name='client',
            name='spouse_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='prénom du conjoint'),
        ),
        migrations.AddField(
            model_name='client',
            name='spouse_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nom du conjoint'),
        ),
        migrations.AddField(
            model_name='client',
            name='spouse_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='téléphone du conjoint'),
        ),
        migrations.AddField(
            model_name='client',
            name='spouse_profession',
            field=models.CharField(blank=True, max_length=150, verbose_name='profession du conjoint'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ifu',
            field=models.CharField(blank=True, max_length=50, verbose_name='numéro IFU'),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('SARL', 'SARL'), ('SA', 'SA'), ('ASSOCIATION', 'Association'), ('INDIVIDUAL', 'Entreprise individuelle'), ('SASU', 'SASU'), ('SAS', 'SAS'), ('EURL', 'EURL'), ('SNC_SCS', 'SNC / SCS')], max_length=20, verbose_name='statut juridique'),
        ),
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name="n° de la pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='téléphone principal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rccm',
            field=models.CharField(blank=True, max_length=50, verbose_name='numéro RCCM'),
        ),
        migrations.AlterField(
            model_name='client',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Généré automatiquement à la création.', max_length=30, verbose_name='matricule'),
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('number', models.CharField(max_length=50, verbose_name='numéro')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='libellé')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='clients.client', verbose_name='client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'téléphone client',
                'verbose_name_plural': 'téléphones client',
                'ordering': ['created_at'],
            },
        ),
    ]
