# Generated by Django 5.1.4 on 2026-07-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_birth_country_client_civility_client_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mother_name',
        ),
        migrations.AddField(
            model_name='client',
            name='father_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='prénom du père'),
        ),
        migrations.AddField(
            model_name='client',
            name='father_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nom du père'),
        ),
        migrations.AddField(
            model_name='client',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='prénom de la mère'),
        ),
        migrations.AddField(
            model_name='client',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nom de la mère'),
        ),
    ]
