# Generated by Django 5.1.4 on 2026-07-14 15:28

import apps.clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_father_name_remove_client_mother_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_document_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.clients.models.client_file_path, verbose_name="scan de la pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='client',
            name='ifu_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.clients.models.client_file_path, verbose_name='scan IFU'),
        ),
        migrations.AlterField(
            model_name='client',
            name='manager_id_document_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.clients.models.client_file_path, verbose_name='scan pièce du gérant'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to=apps.clients.models.client_file_path, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rccm_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.clients.models.client_file_path, verbose_name='scan RCCM'),
        ),
    ]
