# Generated by Django 5.1.4 on 2026-07-22 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_client_manager_details"),
        ("tenants", "0003_tenant_officers_agency_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["tenant", "reference"], name="clients_cli_tenant__92234e_idx"
            ),
        ),
    ]
