# Generated by Django 5.1.4 on 2026-09-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_client_type_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cbs_creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de création CBS (morale)'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='limite de crédit CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_external_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='identifiant externe CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_point_of_service_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='point de service CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_point_of_service_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='libellé point de service CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_registration_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'inscription CBS"),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_situation',
            field=models.JSONField(blank=True, default=dict, help_text='Réponse complète (normalisée + raw) de la dernière situation adhérent renvoyée par le Core Banking.', verbose_name='situation CBS (snapshot)'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dernière synchronisation CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_box',
            field=models.CharField(blank=True, max_length=50, verbose_name='boîte postale'),
        ),
        migrations.AddField(
            model_name='client',
            name='sigle',
            field=models.CharField(blank=True, max_length=50, verbose_name='sigle'),
        ),
    ]
