# Generated by Django 5.1.4 on 2026-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_cbs_situation_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cbs_client_type_id',
            field=models.CharField(blank=True, help_text='idTypeClient', max_length=50, verbose_name='id type client CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_context',
            field=models.CharField(blank=True, help_text='context', max_length=100, verbose_name='contexte réponse CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='distance', max_digits=12, null=True, verbose_name='distance CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_est_valide',
            field=models.BooleanField(blank=True, help_text='estValide', null=True, verbose_name='adhérent valide CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_full_name',
            field=models.CharField(blank=True, help_text='nomAdherent', max_length=255, verbose_name='nom adhérent CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_message',
            field=models.CharField(blank=True, help_text='message', max_length=255, verbose_name='message réponse CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_nationality_id',
            field=models.CharField(blank=True, help_text='idNationalite', max_length=50, verbose_name='id nationalité CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_order_number',
            field=models.CharField(blank=True, help_text='numOrdre', max_length=50, verbose_name="n° d'ordre CBS"),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_profession_id',
            field=models.CharField(blank=True, help_text='idProfession', max_length=50, verbose_name='id profession CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_savings_product_id',
            field=models.CharField(blank=True, help_text='idProduitEpg', max_length=50, verbose_name='id produit épargne CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_sector_id',
            field=models.CharField(blank=True, help_text='idSecteurActivite', max_length=50, verbose_name="id secteur d'activité CBS"),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_signature_count',
            field=models.PositiveIntegerField(blank=True, help_text='nbreSignature', null=True, verbose_name='nombre de signatures CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='cbs_zone_id',
            field=models.CharField(blank=True, help_text='idZone', max_length=50, verbose_name='id zone CBS'),
        ),
        migrations.AddField(
            model_name='client',
            name='head_office',
            field=models.CharField(blank=True, max_length=255, verbose_name='siège social'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cbs_account_number',
            field=models.CharField(blank=True, help_text='numManuel', max_length=50, verbose_name='n° de compte Core Banking'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cbs_client_id',
            field=models.CharField(blank=True, db_index=True, help_text='codeAdherent', max_length=50, verbose_name='matricule Core Banking'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cbs_creation_date',
            field=models.DateField(blank=True, help_text='dateCreation', null=True, verbose_name='date de création CBS'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cbs_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='limitCredit', max_digits=18, null=True, verbose_name='limite de crédit CBS'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cbs_external_id',
            field=models.CharField(blank=True, help_text='externalId', max_length=100, verbose_name='identifiant externe CBS'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cbs_point_of_service_id',
            field=models.CharField(blank=True, help_text='idPointService', max_length=50, verbose_name='point de service CBS'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cbs_point_of_service_name',
            field=models.CharField(blank=True, help_text='nomPointService', max_length=255, verbose_name='libellé point de service CBS'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cbs_registration_date',
            field=models.DateField(blank=True, help_text='dateInscription', null=True, verbose_name="date d'inscription CBS"),
        ),
        migrations.AlterField(
            model_name='client',
            name='cbs_situation',
            field=models.JSONField(blank=True, default=dict, help_text='Copie de sauvegarde de la dernière réponse CBS (normalisée + raw). La source métier reste les colonnes ci-dessus.', verbose_name='situation CBS (copie brute)'),
        ),
    ]
