# Generated by Django 5.1.4 on 2026-07-10 10:58

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('label', models.CharField(max_length=255, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('tracks_expiry', models.BooleanField(default=False, help_text="Génère des alertes à l'approche de la date d'expiration.", verbose_name="suivi d'expiration")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'catégorie de document',
                'verbose_name_plural': 'catégories de documents',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, verbose_name='fichier')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='type MIME')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='taille (octets)')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='empreinte SHA-256')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name="date d'émission")),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="date d'expiration")),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_documentcategory_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type', 'object_id'], name='documents_d_content_ba3031_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'category'], name='documents_d_tenant__e26847_idx'),
        ),
    ]
