# Generated by Django 5.1.4 on 2026-07-14 15:28

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, upload_to=apps.documents.models.document_upload_path, verbose_name='fichier'),
        ),
    ]
