# Generated by Django 5.1.4 on 2026-09-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='origin_key',
            field=models.CharField(blank=True, db_index=True, help_text='Identifiant stable du silo source pour dédoublonnage / purge.', max_length=120, verbose_name="clé d'origine"),
        ),
    ]
