# Generated by Django 5.1.4 on 2026-07-10 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code filiale')),
                ('name', models.CharField(max_length=255, verbose_name='raison sociale')),
                ('country', models.CharField(max_length=100, verbose_name='pays')),
                ('zone', models.CharField(blank=True, help_text='Axe de consolidation Groupe (ex. UEMOA, CEMAC).', max_length=100, verbose_name='zone / région Groupe')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise locale')),
                ('timezone', models.CharField(default='UTC', max_length=64, verbose_name='fuseau horaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='filiale active')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'filiale',
                'verbose_name_plural': 'filiales',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(max_length=20, verbose_name='code agence')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='région')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'agence',
                'verbose_name_plural': 'agences',
                'ordering': ['tenant', 'code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='unique_agency_code_per_tenant')],
            },
        ),
    ]
