# Generated by Django 5.1.4 on 2026-07-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_officers_agency_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="ged_quota_bytes",
            field=models.PositiveBigIntegerField(
                default=10737418240,
                help_text="Plafond de stockage documentaire pour la filiale (défaut 10 Go).",
                verbose_name="quota GED (octets)",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="ged_used_bytes",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Compteur maintenu à l'upload / suppression de documents.",
                verbose_name="GED utilisé (octets)",
            ),
        ),
    ]
