# Generated by Django 5.1.4 on 2026-09-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_long_term_snapshots_ged_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='cbs_point_of_service_id',
            field=models.CharField(blank=True, help_text="Code Perfect / CBS du point de service de l'agence.", max_length=64, verbose_name='identifiant point de service CBS (idPointService)'),
        ),
    ]
