# Generated by Django 5.1.4 on 2026-07-10 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('credits', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(blank=True, max_length=30, verbose_name='référence')),
                ('guarantee_type', models.CharField(choices=[('MORTGAGE', 'Hypothèque'), ('PLEDGE', 'Gage'), ('LIEN', 'Nantissement'), ('DEPOSIT', 'Dépôt de garantie'), ('BANK_GUARANTEE', 'Garantie bancaire'), ('DATION', 'Dation en paiement'), ('JOINT', 'Garantie solidaire'), ('OTHER', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('owners', models.CharField(blank=True, max_length=255, verbose_name='propriétaires')),
                ('expertise_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="valeur d'expertise")),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='valeur actualisée')),
                ('is_insured', models.BooleanField(default=False, verbose_name='assurée')),
                ('insurance_reference', models.CharField(blank=True, max_length=100, verbose_name='réf. assurance')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Mainlevée'), ('REALIZED', 'Réalisée'), ('TRANSFERRED', 'Transférée')], db_index=True, default='ACTIVE', max_length=20)),
                ('last_valuation_date', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantees', to='credits.creditapplication', verbose_name='dossier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guarantees', to='clients.client', verbose_name='client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'garantie',
                'verbose_name_plural': 'garanties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuaranteeMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('movement_type', models.CharField(choices=[('REVALUATION', 'Réévaluation'), ('RELEASE', 'Mainlevée'), ('REALIZATION', 'Réalisation'), ('TRANSFER', 'Transfert')], max_length=20)),
                ('movement_date', models.DateField(verbose_name='date')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='valeur')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='guarantees.guarantee', verbose_name='garantie')),
                ('target_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_transfers_in', to='credits.creditapplication', verbose_name='dossier cible (transfert)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'mouvement de garantie',
                'verbose_name_plural': 'mouvements de garantie',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddIndex(
            model_name='guarantee',
            index=models.Index(fields=['tenant', 'status', 'guarantee_type'], name='guarantees__tenant__077864_idx'),
        ),
    ]
