# Generated by Django 5.1.4 on 2026-07-14 12:23

import apps.guarantees.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantees', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantee',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='numéro de compte'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'acquisition"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='acquisition_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name="valeur d'acquisition"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='information complémentaire'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='adresse du bien'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='solde'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='marque'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='numéro de châssis'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='deposit_maturity_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'échéance du dépôt"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='document_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'établissement du document"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='numéro du document'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='document_scan',
            field=models.FileField(blank=True, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan du document'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='document_type',
            field=models.CharField(blank=True, choices=[('LAND_TITLE', 'Titre foncier'), ('ATTRIBUTION_CERT', "Attestation d'attribution")], max_length=20, verbose_name='type de document'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='numéro du moteur'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='estimation_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'estimation"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='expertise_certificate_scan',
            field=models.FileField(blank=True, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name="scan certificat d'expertise"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='expertise_date',
            field=models.DateField(blank=True, null=True, verbose_name="date de l'expertise"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='expertise_firm',
            field=models.CharField(blank=True, max_length=200, verbose_name="cabinet d'expertise"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='expertise_report_scan',
            field=models.FileField(blank=True, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name="scan du rapport d'expertise"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='financial_type',
            field=models.CharField(blank=True, choices=[('DAT', 'Dépôt à terme (DAT)'), ('SAVINGS', 'Épargne'), ('SECURITY', 'Titre')], max_length=15, verbose_name='type de garantie financière'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='first_registration_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='année de première mise en circulation'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='insurance_scan',
            field=models.FileField(blank=True, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan assurance'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='isin_code',
            field=models.CharField(blank=True, max_length=150, verbose_name='code ISIN / nom de la valeur'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='lease_contract_scan',
            field=models.FileField(blank=True, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan du contrat de bail'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='legal_situation_certificate_scan',
            field=models.FileField(blank=True, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan certificat de situation juridique'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='ltv_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valeur à considérer / montant du prêt (calculé).', max_digits=8, null=True, verbose_name='ratio LTV'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='matrimonial_regime',
            field=models.CharField(blank=True, choices=[('COMMUNITY', 'Communauté de biens'), ('SEPARATION', 'Séparation de biens')], max_length=15, verbose_name='régime matrimonial'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='mechanical_expertise_scan',
            field=models.FileField(blank=True, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name="scan rapport d'expertise mécanique"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='modèle'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='occupancy_status',
            field=models.CharField(blank=True, choices=[('FREE', 'Libre'), ('FAMILY_HOME', 'Domicile familial'), ('DEVELOPER', 'Occupé par le promoteur'), ('RENTED', 'En location')], max_length=15, verbose_name="statut d'occupation"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='origin_certificate_scan',
            field=models.FileField(blank=True, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name="scan certificat d'origine / facture"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='owner_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='prénom du propriétaire'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='owner_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nom du propriétaire'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='owner_marital_status',
            field=models.CharField(blank=True, max_length=15, verbose_name='situation matrimoniale du propriétaire'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='pledge_category',
            field=models.CharField(blank=True, choices=[('VEHICLE', 'Moyen roulant'), ('VALUABLE', 'Objet de valeur')], max_length=15, verbose_name='catégorie de gage'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='pledge_deed_scan',
            field=models.FileField(blank=True, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan acte de nantissement / blocage'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='power',
            field=models.CharField(blank=True, max_length=50, verbose_name='puissance'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='purchase_invoice_scan',
            field=models.FileField(blank=True, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name="scan facture d'achat"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='raw_material_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='cours actuel de la matière première'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='registration',
            field=models.CharField(blank=True, max_length=50, verbose_name='immatriculation'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='registration_card_scan',
            field=models.FileField(blank=True, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan carte grise'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='remuneration_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='taux de rémunération (%)'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='resale_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='valeur estimée à la revente'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='security_discount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='décote de sécurité (%)'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='technical_inspection_scan',
            field=models.FileField(blank=True, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan visite technique'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='value_to_consider',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='valeur à considérer'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='volatility_history',
            field=models.TextField(blank=True, verbose_name='historique de volatilité'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='guarantee_type',
            field=models.CharField(choices=[('MORTGAGE', 'Hypothèque (garantie réelle immobilière)'), ('PLEDGE', 'Gage (garantie réelle mobilière)'), ('FINANCIAL', 'Garantie financière'), ('LIEN', 'Nantissement'), ('DEPOSIT', 'Dépôt de garantie'), ('BANK_GUARANTEE', 'Garantie bancaire'), ('DATION', 'Dation en paiement'), ('JOINT', 'Garantie solidaire'), ('OTHER', 'Autre')], max_length=20),
        ),
        migrations.CreateModel(
            name='GuaranteePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('image', models.ImageField(upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='photo')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='légende')),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='guarantees.guarantee', verbose_name='garantie')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'photo de garantie',
                'verbose_name_plural': 'photos de garantie',
                'ordering': ['created_at'],
            },
        ),
    ]
