# Generated by Django 5.1.4 on 2026-07-14 15:28

import apps.guarantees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantees', '0002_guarantee_account_number_guarantee_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='document_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan du document'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='expertise_certificate_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name="scan certificat d'expertise"),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='expertise_report_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name="scan du rapport d'expertise"),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='insurance_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan assurance'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='lease_contract_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan du contrat de bail'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='legal_situation_certificate_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan certificat de situation juridique'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='mechanical_expertise_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name="scan rapport d'expertise mécanique"),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='origin_certificate_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name="scan certificat d'origine / facture"),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='pledge_deed_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan acte de nantissement / blocage'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='purchase_invoice_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name="scan facture d'achat"),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='registration_card_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan carte grise'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='technical_inspection_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='scan visite technique'),
        ),
        migrations.AlterField(
            model_name='guaranteephoto',
            name='image',
            field=models.ImageField(max_length=255, upload_to=apps.guarantees.models.guarantee_file_path, verbose_name='photo'),
        ),
    ]
