# Generated by Django 5.1.4 on 2026-09-04 23:37

import apps.guarantees.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0026_cbs_referentials'),
        ('guarantees', '0013_cbs_currency_default_xof'),
        ('tenants', '0005_cbs_disbursement_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantee',
            name='formalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='formalisation clôturée le'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='registration_authority',
            field=models.CharField(blank=True, help_text='Ex. conservation foncière, greffe, RCCM…', max_length=255, verbose_name="organisme d'enregistrement"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'enregistrement"),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, verbose_name="n° d'enregistrement / publicité"),
        ),
        migrations.AlterField(
            model_name='guaranteemovement',
            name='movement_type',
            field=models.CharField(choices=[('REVALUATION', 'Réévaluation'), ('RELEASE', 'Mainlevée'), ('REALIZATION', 'Réalisation'), ('TRANSFER', 'Transfert'), ('RENEWAL', 'Reconduction'), ('FORMALIZATION', 'Formalisation')], max_length=20),
        ),
        migrations.CreateModel(
            name='GuaranteeFormalizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='référence')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('IN_PROGRESS', 'En cours'), ('IN_APPROVAL', 'En validation'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('RETURNED', 'Retournée'), ('COMPLETED', 'Clôturée'), ('CANCELLED', 'Annulée')], db_index=True, default='DRAFT', max_length=20)),
                ('legal_stage', models.CharField(choices=[('NOT_SENT', 'Non soumis chez le notaire'), ('AT_NOTARY', 'Chez le notaire'), ('AWAITING_SIGNATURE', 'En attente de signature'), ('SIGNED', 'Acte signé'), ('PENDING_REGISTRATION', 'Enregistrement / publicité en cours'), ('REGISTERED', 'Enregistré'), ('DONE', 'Formalisation terminée')], db_index=True, default='NOT_SENT', max_length=30, verbose_name='étape juridique')),
                ('notary_name', models.CharField(blank=True, max_length=255, verbose_name='notaire / étude')),
                ('notary_reference', models.CharField(blank=True, max_length=100, verbose_name='référence dossier notaire')),
                ('sent_to_notary_at', models.DateField(blank=True, null=True, verbose_name='transmis au notaire le')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='retour prévu')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name="n° d'enregistrement")),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name="date d'enregistrement")),
                ('registration_authority', models.CharField(blank=True, max_length=255, verbose_name='organisme')),
                ('acte_file', models.FileField(blank=True, null=True, upload_to=apps.guarantees.models.formalization_acte_upload_path, verbose_name='projet / acte')),
                ('acte_signed_file', models.FileField(blank=True, null=True, upload_to=apps.guarantees.models.formalization_acte_upload_path, verbose_name='acte signé')),
                ('registration_proof', models.FileField(blank=True, null=True, upload_to=apps.guarantees.models.formalization_acte_upload_path, verbose_name="preuve d'enregistrement")),
                ('fees_client_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='frais client')),
                ('fees_institution_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='frais institution')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='clôturée le')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formalization_requests', to='tenants.agency', verbose_name='agence')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formalization_requests', to='credits.creditapplication', verbose_name='dossier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formalization_requests', to='guarantees.guarantee', verbose_name='garantie')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'formalisation de garantie',
                'verbose_name_plural': 'formalisations de garantie',
                'ordering': ['-created_at'],
                'permissions': [('initiate_guaranteeformalizationrequest', 'Peut initier une formalisation de garantie')],
            },
        ),
        migrations.CreateModel(
            name='FormalizationFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('fee_type', models.CharField(choices=[('NOTARY', 'Notaire / acte'), ('REGISTRATION', 'Enregistrement / publicité'), ('BAILIFF', 'Huissier'), ('ADMIN', 'Frais administratifs'), ('OTHER', 'Divers')], default='OTHER', max_length=20)),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='montant')),
                ('payer', models.CharField(choices=[('CLIENT', 'Client'), ('INSTITUTION', 'Institution')], default='CLIENT', max_length=20)),
                ('fee_date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('recoverable', models.BooleanField(default=True, verbose_name='récupérable')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
                ('formalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='guarantees.guaranteeformalizationrequest', verbose_name='formalisation')),
            ],
            options={
                'verbose_name': 'frais de formalisation',
                'verbose_name_plural': 'frais de formalisation',
                'ordering': ['fee_date', 'created_at'],
            },
        ),
    ]
