# Generated by Django 5.1.4 on 2026-07-20 10:27

import apps.contracts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('credits', '0014_financialanalysis_chemicals_pesticides_and_more'),
        ('tenants', '0002_tenant_branding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='code')),
                ('name', models.CharField(max_length=200, verbose_name='intitulé du contrat')),
                ('category', models.CharField(blank=True, choices=[('NOTIFICATION', 'Notification de crédit'), ('LOAN', 'Contrat de prêt'), ('SURETY', 'Cautionnement'), ('PLEDGE_VEHICLE', 'Gage véhicule'), ('PLEDGE_JEWELRY', 'Gage bijoux'), ('PLEDGE_SHARES', "Nantissement d'actions"), ('SALARY_ASSIGNMENT', 'Cession sur salaire'), ('PROMISSORY_NOTE', 'Billet à ordre'), ('FIDUCIARY_TRANSFER', 'Transfert fiduciaire'), ('OTHER', 'Autre')], default='OTHER', max_length=30, verbose_name='catégorie')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('engine', models.CharField(choices=[('DOCX', 'Word (.docx)'), ('XLSX', 'Excel (.xlsx)')], default='DOCX', max_length=10, verbose_name='moteur')),
                ('file', models.FileField(max_length=255, upload_to=apps.contracts.models.template_file_path, verbose_name='modèle')),
                ('applies_to', models.CharField(choices=[('ANY', 'Tous les clients'), ('INDIVIDUAL', 'Particuliers uniquement'), ('CORPORATE', 'Entreprises uniquement')], default='ANY', max_length=15, verbose_name="s'applique à")),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='montant minimum')),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='montant maximum')),
                ('extra_fields', models.JSONField(blank=True, default=list, help_text="Liste [{key, label, type}] de variables saisies à la génération (ex. nom d'un témoin, mention spéciale).", verbose_name='champs additionnels')),
                ('is_required', models.BooleanField(default=False, help_text="Le dossier ne pourra être décaissé qu'une fois ce contrat généré.", verbose_name='obligatoire avant décaissement')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('product', models.ForeignKey(blank=True, help_text='Limiter ce modèle à un produit de crédit précis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates', to='catalog.creditproduct', verbose_name='produit (optionnel)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'modèle de contrat',
                'verbose_name_plural': 'modèles de contrats',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('template_name', models.CharField(max_length=200, verbose_name='intitulé')),
                ('category', models.CharField(blank=True, max_length=30, verbose_name='catégorie')),
                ('file', models.FileField(max_length=255, upload_to=apps.contracts.models.generated_file_path, verbose_name='document généré')),
                ('context_snapshot', models.JSONField(blank=True, default=dict, verbose_name='variables utilisées')),
                ('extra_values', models.JSONField(blank=True, default=dict, verbose_name='valeurs saisies manuellement')),
                ('status', models.CharField(choices=[('GENERATED', 'Généré'), ('SIGNED', 'Signé'), ('CANCELLED', 'Annulé')], default='GENERATED', max_length=15)),
                ('signed_file', models.FileField(blank=True, max_length=255, upload_to=apps.contracts.models.signed_file_path, verbose_name='scan signé')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='signé le')),
                ('notes', models.TextField(blank=True, verbose_name='observations')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contracts', to='credits.creditapplication', verbose_name='dossier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_contracts', to='contracts.contracttemplate', verbose_name='modèle')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'contrat généré',
                'verbose_name_plural': 'contrats générés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contracttemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='contracts_c_tenant__474f81_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcontract',
            index=models.Index(fields=['tenant', 'application'], name='contracts_g_tenant__133ecc_idx'),
        ),
    ]
