# Generated by Django 5.1.4 on 2026-07-10 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='référence dossier')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='montant demandé')),
                ('duration_months', models.PositiveIntegerField(verbose_name='durée (mois)')),
                ('purpose', models.TextField(blank=True, verbose_name='objet du financement')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('IN_APPROVAL', "En cours d'approbation"), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('RETURNED', 'Retourné pour correction'), ('CONTRACT_GENERATED', 'Contrat généré'), ('DISBURSED', 'Décaissé'), ('CLOSED', 'Clôturé'), ('CANCELLED', 'Annulé')], db_index=True, default='DRAFT', max_length=20)),
                ('risk_level', models.PositiveIntegerField(blank=True, null=True, verbose_name='niveau de risque (1-5)')),
                ('internal_rating', models.CharField(blank=True, max_length=10, verbose_name='notation interne')),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='montant approuvé')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='taux appliqué (%)')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='date de décision')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='soumis le')),
                ('disbursed_at', models.DateTimeField(blank=True, null=True, verbose_name='décaissé le')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_applications', to='tenants.agency', verbose_name='agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_applications', to='clients.client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_applications', to='catalog.creditproduct', verbose_name='produit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'dossier de crédit',
                'verbose_name_plural': 'dossiers de crédit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('visit_date', models.DateField(verbose_name='date de visite')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('report', models.TextField(blank=True, verbose_name='compte rendu')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_visits', to='credits.creditapplication', verbose_name='dossier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
                ('visited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'visite terrain',
                'verbose_name_plural': 'visites terrain',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='revenus mensuels')),
                ('monthly_charges', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='charges mensuelles')),
                ('existing_debt', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='endettement existant')),
                ('debt_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="taux d'endettement (%)")),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_analysis', to='credits.creditapplication', verbose_name='dossier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'analyse financière',
                'verbose_name_plural': 'analyses financières',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='capital')),
                ('interest_rate', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='taux (%)')),
                ('duration_months', models.PositiveIntegerField(verbose_name='durée (mois)')),
                ('disbursed_at', models.DateField(verbose_name='date de décaissement')),
                ('first_due_date', models.DateField(verbose_name='première échéance')),
                ('status', models.CharField(choices=[('ACTIVE', 'En cours'), ('CLOSED', 'Soldé'), ('DEFAULTED', 'En défaut')], default='ACTIVE', max_length=20)),
                ('core_banking_reference', models.CharField(blank=True, max_length=100)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='credits.creditapplication', verbose_name='dossier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'prêt',
                'verbose_name_plural': 'prêts',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('number', models.PositiveIntegerField(verbose_name="n° d'échéance")),
                ('due_date', models.DateField(db_index=True, verbose_name="date d'échéance")),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'À échoir'), ('PAID', 'Payée'), ('PARTIAL', 'Partielle'), ('OVERDUE', 'En retard')], db_index=True, default='PENDING', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='credits.loan', verbose_name='prêt')),
            ],
            options={
                'verbose_name': 'échéance',
                'verbose_name_plural': 'échéances',
                'ordering': ['loan', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='creditapplication',
            index=models.Index(fields=['tenant', 'status'], name='credits_cre_tenant__a0ff18_idx'),
        ),
        migrations.AddIndex(
            model_name='creditapplication',
            index=models.Index(fields=['tenant', '-created_at'], name='credits_cre_tenant__32e566_idx'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('loan', 'number'), name='unique_installment_number_per_loan'),
        ),
    ]
