# Generated by Django 5.1.4 on 2026-07-14 09:23

import apps.credits.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('credits', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='activity',
            field=models.CharField(blank=True, max_length=200, verbose_name='activité du client'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='activity_start_date',
            field=models.DateField(blank=True, null=True, verbose_name="date de création de l'activité"),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='amount_proposed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='montant proposé'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='avg_client_payment_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='délai moyen de paiement clients (jours)'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='avg_supplier_payment_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='délai moyen de paiement fournisseurs (jours)'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='catchment_area',
            field=models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('NATIONAL', 'National'), ('EXPORT', 'Export')], max_length=15, verbose_name='zone de chalandise'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='clientele',
            field=models.CharField(blank=True, max_length=255, verbose_name='clientèle'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='competitive_advantage',
            field=models.TextField(blank=True, verbose_name='avantage concurrentiel'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='current_stock_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='niveau de stock actuel'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='direct_competitors_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='nombre de concurrents directs'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='employees_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="nombre d'employés"),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='exact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='adresse exacte'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='fees_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='frais de dossier (%)'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='first_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de première échéance'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='fixed_charges_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='charges fixes mensuelles estimées'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='has_ongoing_credit',
            field=models.BooleanField(default=False, verbose_name='crédit en cours'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='last_due_date',
            field=models.DateField(blank=True, help_text='Calculée automatiquement.', null=True, verbose_name='date de dernière échéance'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='main_suppliers_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='nombre de principaux fournisseurs'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='main_suppliers_names',
            field=models.TextField(blank=True, verbose_name='noms des principaux fournisseurs'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='monthly_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='marge mensuelle estimée'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='monthly_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name="chiffre d'affaires mensuel estimé"),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='ongoing_credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='montant du crédit en cours'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='ongoing_credit_institution',
            field=models.CharField(blank=True, max_length=200, verbose_name='institution du crédit en cours'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='ongoing_credit_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='mensualité du crédit en cours'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='ongoing_credit_outstanding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='encours restant du crédit en cours'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='periodicity',
            field=models.CharField(choices=[('DAILY', 'Journalier'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuelle'), ('QUARTERLY', 'Trimestrielle'), ('SEMIANNUAL', 'Semestrielle'), ('ANNUAL', 'Annuelle')], default='MONTHLY', max_length=15, verbose_name='périodicité'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='premises_status',
            field=models.CharField(blank=True, choices=[('OWNER', 'Propriétaire'), ('TENANT', 'Locataire')], max_length=15, verbose_name="statut d'occupation des locaux"),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='repayment_mechanism',
            field=models.CharField(blank=True, choices=[('CONSTANT', 'Échéances constantes'), ('DEGRESSIVE', 'Amortissement dégressif'), ('IN_FINE', 'In fine (capital à terme)'), ('BULLET', 'Remboursement unique (bullet)')], max_length=20, verbose_name='mécanisme de remboursement'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='request_letter_scan',
            field=models.FileField(blank=True, upload_to=apps.credits.models.credit_file_path, verbose_name='scan de la lettre de demande'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='seasonality',
            field=models.TextField(blank=True, verbose_name="saisonnalité de l'activité"),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='tax_regime',
            field=models.CharField(blank=True, choices=[('SYNTHETIC', 'Impôt synthétique'), ('REAL', 'Régime réel'), ('SPECIFIC_EXEMPTION', 'Exonérations spécifiques'), ('INFORMAL', 'Secteur informel')], max_length=20, verbose_name='régime fiscal'),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name="taux d'intérêt (%)"),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_applications', to='catalog.creditproduct', verbose_name='produit (type de crédit)'),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='détails de la demande'),
        ),
        migrations.CreateModel(
            name='StockPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('image', models.ImageField(upload_to=apps.credits.models.credit_file_path, verbose_name='photo du stock')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='légende')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_photos', to='credits.creditapplication', verbose_name='dossier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'photo de stock',
                'verbose_name_plural': 'photos de stock',
                'ordering': ['created_at'],
            },
        ),
    ]
