# Generated by Django 5.1.4 on 2026-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_creditapplication_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='analysis',
            field=models.TextField(blank=True, verbose_name='analyse du chargé de dossier'),
        ),
    ]
