# Generated by Django 5.1.4 on 2026-07-14 15:28

import apps.credits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_creditapplication_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='request_letter_scan',
            field=models.FileField(blank=True, max_length=255, upload_to=apps.credits.models.credit_file_path, verbose_name='scan de la lettre de demande'),
        ),
        migrations.AlterField(
            model_name='stockphoto',
            name='image',
            field=models.ImageField(max_length=255, upload_to=apps.credits.models.credit_file_path, verbose_name='photo du stock'),
        ),
    ]
