# Generated by Django 5.1.4 on 2026-07-14 19:09

import apps.credits.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_creditapplication_submitted_by'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialanalysis',
            name='analysis_date',
            field=models.DateField(blank=True, null=True, verbose_name="date de l'analyse"),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='cash_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='trésorerie (caisse + banque)'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='client_type',
            field=models.CharField(blank=True, help_text="Renseigné automatiquement d'après le client.", max_length=20, verbose_name='type de client'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='cogs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="coût d'achat des marchandises vendues"),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='depreciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='amortissements'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='dscr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='couverture du service de la dette (DSCR)'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='education_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='scolarité / éducation'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='existing_debt_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='mensualités des crédits en cours'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='financial_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='charges financières'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='fixed_assets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='immobilisations'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='food_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='alimentation'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='health_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='santé'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='internal_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='score interne'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='new_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='échéance du nouveau crédit'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='ongoing_credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='encours crédits en cours'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='op_maintenance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='entretien'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='op_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="autres charges d'exploitation"),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='op_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='loyer'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='op_salaries',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='salaires'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='op_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='impôts & patente'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='op_telecom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='téléphone / internet'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='op_transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='transport / carburant'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='op_utilities',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='eau / électricité'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='other_activity_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="revenus d'activité annexe"),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='other_household_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='autres charges du ménage'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='other_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='autres revenus'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='receivables',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='créances clients'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('FAVORABLE', 'Favorable'), ('CONDITIONAL', 'Favorable sous conditions'), ('UNFAVORABLE', 'Défavorable')], max_length=15, verbose_name='recommandation'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='reference_period',
            field=models.CharField(choices=[('MONTHLY', 'Mensuelle'), ('QUARTERLY', 'Trimestrielle'), ('ANNUAL', 'Annuelle')], default='MONTHLY', max_length=15, verbose_name='période de référence'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='rent_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='loyer / logement'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='rental_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='revenus locatifs / rente'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='repayment_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='capacité de remboursement'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='salary_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='salaire net'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='spouse_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='revenus du conjoint'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='stock_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='stock'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='supplier_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='dettes fournisseurs'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='transport_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='transport'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="chiffre d'affaires"),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='utilities_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='eau / électricité / téléphone'),
        ),
        migrations.AlterField(
            model_name='financialanalysis',
            name='comment',
            field=models.TextField(blank=True, verbose_name="avis / commentaire de l'analyste"),
        ),
        migrations.AlterField(
            model_name='financialanalysis',
            name='debt_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="taux d'endettement (%)"),
        ),
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('file', models.FileField(max_length=255, upload_to=apps.credits.models.credit_file_path, verbose_name='fichier')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='libellé')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='credits.financialanalysis', verbose_name='analyse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'pièce justificative (analyse)',
                'verbose_name_plural': 'pièces justificatives (analyse)',
                'ordering': ['created_at'],
            },
        ),
    ]
