# Generated by Django 5.1.4 on 2026-07-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_financialanalysis_analysis_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditapplication',
            name='current_stock_level',
        ),
        migrations.RemoveField(
            model_name='creditapplication',
            name='fixed_charges_monthly',
        ),
        migrations.RemoveField(
            model_name='creditapplication',
            name='has_ongoing_credit',
        ),
        migrations.RemoveField(
            model_name='creditapplication',
            name='monthly_margin',
        ),
        migrations.RemoveField(
            model_name='creditapplication',
            name='monthly_turnover',
        ),
        migrations.RemoveField(
            model_name='creditapplication',
            name='ongoing_credit_amount',
        ),
        migrations.RemoveField(
            model_name='creditapplication',
            name='ongoing_credit_institution',
        ),
        migrations.RemoveField(
            model_name='creditapplication',
            name='ongoing_credit_monthly',
        ),
        migrations.RemoveField(
            model_name='creditapplication',
            name='ongoing_credit_outstanding',
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='existing_debt_initial_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='montant initial du crédit en cours'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='existing_debt_institution',
            field=models.CharField(blank=True, max_length=200, verbose_name='institution du crédit en cours'),
        ),
    ]
