# Generated by Django 5.1.4 on 2026-07-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0007_remove_creditapplication_current_stock_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='avg_monthly_credit_movements',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='mouvements créditeurs mensuels moyens'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='bceao_check_done',
            field=models.BooleanField(default=False, verbose_name='consultation Centrale des Risques BCEAO effectuée'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='bceao_check_result',
            field=models.TextField(blank=True, verbose_name='résultat Centrale des Risques'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='beneficial_owner',
            field=models.CharField(blank=True, max_length=200, verbose_name='bénéficiaire effectif'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='client_account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name="numéro de compte dans l'institution"),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('CIVIL_SERVANT', 'Fonctionnaire'), ('INDEPENDENT', 'Indépendant'), ('RETIRED', 'Retraité'), ('OTHER', 'Autre')], max_length=20, verbose_name='type de contrat'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='credit_history_notes',
            field=models.TextField(blank=True, verbose_name='historique de crédit / antécédents'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='dependents_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='nombre de personnes à charge'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='document_checklist',
            field=models.JSONField(blank=True, default=list, help_text='Liste [{label, provided}] des pièces obligatoires.', verbose_name='pièces du dossier'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='employeur'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='financed_quota',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculée automatiquement : montant demandé / coût total.', max_digits=6, null=True, verbose_name='quotité financée (%)'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='funds_origin',
            field=models.CharField(blank=True, max_length=255, verbose_name='origine des fonds / apport'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='has_credit_insurance',
            field=models.BooleanField(default=False, verbose_name='assurance décès-invalidité (ADI)'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='has_past_incidents',
            field=models.BooleanField(default=False, verbose_name='incidents de remboursement antérieurs'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=200, verbose_name="compagnie d'assurance"),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='insurance_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name="prime d'assurance"),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='is_pep',
            field=models.BooleanField(default=False, verbose_name='personne politiquement exposée (PPE)'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='job_seniority_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="ancienneté dans l'emploi (mois)"),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='personal_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='apport personnel'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='project_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='coût total du projet'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='purpose_type',
            field=models.CharField(blank=True, choices=[('WORKING_CAPITAL', 'Fonds de roulement'), ('EQUIPMENT', 'Investissement / équipement'), ('STOCK', 'Achat de stock'), ('REAL_ESTATE', 'Immobilier'), ('TREASURY', 'Trésorerie'), ('CONSUMPTION', 'Consommation'), ('OTHER', 'Autre')], max_length=20, verbose_name='objet du financement'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='relationship_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='début de la relation'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='risk_class',
            field=models.CharField(blank=True, choices=[('A', 'A — Excellent'), ('B', 'B — Bon'), ('C', 'C — Moyen'), ('D', 'D — Faible'), ('E', 'E — Très risqué')], max_length=1, verbose_name='classe de risque'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='salary_domiciliation',
            field=models.BooleanField(default=False, verbose_name="domiciliation du salaire dans l'institution"),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='special_conditions',
            field=models.TextField(blank=True, verbose_name='conditions particulières'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='suspensive_conditions',
            field=models.TextField(blank=True, verbose_name='conditions suspensives (avant décaissement)'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='cashflow_comment',
            field=models.TextField(blank=True, verbose_name='commentaire sur la trésorerie prévisionnelle'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='projected_monthly_inflows',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='encaissements prévisionnels'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='projected_monthly_outflows',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='décaissements prévisionnels'),
        ),
    ]
