# Generated by Django 5.1.4 on 2026-07-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0008_creditapplication_avg_monthly_credit_movements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='mandatory_savings_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='% du capital prélevé en épargne à chaque échéance (0 = non applicable).', max_digits=6, null=True, verbose_name="taux d'épargne obligatoire (%)"),
        ),
        migrations.AddField(
            model_name='installment',
            name='savings_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='épargne obligatoire'),
        ),
        migrations.AddField(
            model_name='loan',
            name='mandatory_savings_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name="taux d'épargne obligatoire (%)"),
        ),
    ]
