# Generated by Django 5.1.4 on 2026-07-16 14:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0012_analysis_deep_and_thresholds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisthreshold',
            options={'verbose_name': "seuils d'analyse financière", 'verbose_name_plural': "seuils d'analyse financière"},
        ),
        migrations.AlterField(
            model_name='analysisthreshold',
            name='min_dscr',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.2'), max_digits=6, verbose_name='DSCR minimum'),
        ),
        migrations.AlterField(
            model_name='analysisthreshold',
            name='transferable_quota_fraction',
            field=models.DecimalField(decimal_places=2, default=Decimal('33.33'), max_digits=6, verbose_name='quotité cessible du salaire (%)'),
        ),
        migrations.AlterField(
            model_name='financialanalysis',
            name='existing_debt_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='mensualités des crédits en cours (total consolidé)'),
        ),
        migrations.AlterField(
            model_name='financialanalysis',
            name='ongoing_credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='encours crédits en cours (dettes financières)'),
        ),
    ]
