# Generated by Django 5.1.4 on 2026-07-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0013_alter_analysisthreshold_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialanalysis',
            name='chemicals_pesticides',
            field=models.CharField(blank=True, choices=[('GOOD', 'Satisfaisante'), ('IMPROVE', 'À améliorer'), ('BAD', 'Problématique')], max_length=10, verbose_name='usage produits chimiques / pesticides'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='child_forced_labor_risk',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10, verbose_name='risque travail des enfants / forcé'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='client_concentration',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10, verbose_name='concentration de la clientèle'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='climate_sensitivity',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10, verbose_name='sensibilité climatique'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='community_impact',
            field=models.CharField(blank=True, choices=[('GOOD', 'Satisfaisante'), ('IMPROVE', 'À améliorer'), ('BAD', 'Problématique')], max_length=10, verbose_name='impact sur les communautés riveraines'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='competition_intensity',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10, verbose_name='intensité concurrentielle'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='eia_done',
            field=models.BooleanField(default=False, verbose_name="étude d'impact environnemental réalisée"),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='eia_required',
            field=models.BooleanField(default=False, verbose_name="étude d'impact environnemental requise"),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='env_permit_obtained',
            field=models.BooleanField(default=False, verbose_name='autorisation environnementale obtenue'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='env_permit_required',
            field=models.BooleanField(default=False, verbose_name='autorisation environnementale requise'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='es_action_required',
            field=models.BooleanField(default=False, verbose_name="plan d'action E&S exigé"),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='es_category',
            field=models.CharField(blank=True, choices=[('A', 'A — Risque élevé'), ('B', 'B — Risque moyen'), ('C', 'C — Risque faible')], max_length=1, verbose_name='catégorie de risque E&S'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='es_comment',
            field=models.TextField(blank=True, verbose_name='commentaire E&S'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='es_insurance',
            field=models.BooleanField(default=False, verbose_name='assurances E&S (pollution / RC)'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='es_mitigation_plan',
            field=models.TextField(blank=True, verbose_name="plan d'action / mesures d'atténuation (PGES)"),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='es_regulatory_compliance',
            field=models.BooleanField(default=True, verbose_name='conformité réglementaire E&S'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='es_risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10, verbose_name='niveau de risque E&S global'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='exclusion_list_ok',
            field=models.BooleanField(default=True, verbose_name="activité hors liste d'exclusion"),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='fx_exposure',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10, verbose_name='exposition aux devises / importations'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='input_price_sensitivity',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10, verbose_name='sensibilité au prix des intrants'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='jobs_created',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='emplois créés'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='jobs_maintained',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='emplois maintenus'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='jobs_women',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='dont emplois féminins'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='jobs_youth',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='dont emplois jeunes'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='land_resettlement_risk',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10, verbose_name='enjeux fonciers / réinstallation'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='market_dynamic',
            field=models.CharField(blank=True, choices=[('GROWTH', 'En croissance'), ('MATURE', 'Mature / stable'), ('DECLINE', 'En déclin')], max_length=10, verbose_name='dynamique du marché'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='nuisances_emissions',
            field=models.CharField(blank=True, choices=[('GOOD', 'Satisfaisante'), ('IMPROVE', 'À améliorer'), ('BAD', 'Problématique')], max_length=10, verbose_name='nuisances / émissions / pollution'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='occupational_safety',
            field=models.CharField(blank=True, choices=[('GOOD', 'Satisfaisante'), ('IMPROVE', 'À améliorer'), ('BAD', 'Problématique')], max_length=10, verbose_name='sécurité & santé au travail'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='permit_reference',
            field=models.CharField(blank=True, max_length=150, verbose_name="référence de l'autorisation"),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='regulatory_sensitivity',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10, verbose_name='sensibilité réglementaire / fiscale'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='resource_use',
            field=models.CharField(blank=True, choices=[('GOOD', 'Satisfaisante'), ('IMPROVE', 'À améliorer'), ('BAD', 'Problématique')], max_length=10, verbose_name="usage de l'eau / énergie"),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='seasonality_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10, verbose_name='intensité de la saisonnalité'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='sector',
            field=models.CharField(blank=True, choices=[('AGRICULTURE', 'Agriculture / élevage / pêche'), ('COMMERCE', 'Commerce / négoce'), ('INDUSTRY', 'Industrie / transformation'), ('CONSTRUCTION', 'BTP / construction'), ('TRANSPORT', 'Transport / logistique'), ('SERVICES', 'Services'), ('CRAFTS', 'Artisanat'), ('ICT', 'TIC / numérique'), ('TOURISM', 'Tourisme / hôtellerie / restauration'), ('HEALTH', 'Santé'), ('EDUCATION', 'Éducation'), ('ENERGY', 'Énergie / mines'), ('OTHER', 'Autre')], max_length=20, verbose_name="secteur d'activité"),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='sector_comment',
            field=models.TextField(blank=True, verbose_name='commentaire sectoriel'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='sector_outlook',
            field=models.TextField(blank=True, verbose_name='perspectives du secteur'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='sector_risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10, verbose_name='niveau de risque sectoriel'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='sub_sector',
            field=models.CharField(blank=True, max_length=200, verbose_name='sous-secteur / filière'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='supplier_dependency',
            field=models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10, verbose_name='dépendance aux fournisseurs'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='value_chain_position',
            field=models.CharField(blank=True, choices=[('INPUTS', 'Intrants / approvisionnement'), ('PRODUCTION', 'Production'), ('PROCESSING', 'Transformation'), ('DISTRIBUTION', 'Distribution / commerce'), ('SERVICES', 'Services')], max_length=20, verbose_name='position dans la chaîne de valeur'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='waste_management',
            field=models.CharField(blank=True, choices=[('GOOD', 'Satisfaisante'), ('IMPROVE', 'À améliorer'), ('BAD', 'Problématique')], max_length=10, verbose_name='gestion des déchets / effluents'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='working_conditions',
            field=models.CharField(blank=True, choices=[('GOOD', 'Satisfaisante'), ('IMPROVE', 'À améliorer'), ('BAD', 'Problématique')], max_length=10, verbose_name='conditions de travail'),
        ),
    ]
