# Generated by Django 5.1.4 on 2026-07-22 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("clients", "0008_medium_term_mfa_and_indexes"),
        ("credits", "0018_remove_financialanalysis_legacy_fields"),
        ("tenants", "0003_tenant_officers_agency_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="creditapplication",
            index=models.Index(
                fields=["tenant", "reference"], name="credits_cre_tenant__b63516_idx"
            ),
        ),
    ]
