# Generated by Django 5.1.4 on 2026-09-04 13:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0021_alter_loan_status_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisthreshold',
            name='haircut_financial_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='haircut DAT / épargne (%)'),
        ),
        migrations.AddField(
            model_name='analysisthreshold',
            name='haircut_financial_security',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=6, verbose_name='haircut titres (%)'),
        ),
        migrations.AddField(
            model_name='analysisthreshold',
            name='haircut_jewelry',
            field=models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=6, verbose_name='haircut bijoux / objets (%)'),
        ),
        migrations.AddField(
            model_name='analysisthreshold',
            name='haircut_mortgage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='haircut hypothèque (%)'),
        ),
        migrations.AddField(
            model_name='analysisthreshold',
            name='haircut_other',
            field=models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=6, verbose_name='haircut autres garanties (%)'),
        ),
        migrations.AddField(
            model_name='analysisthreshold',
            name='haircut_vehicle',
            field=models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=6, verbose_name='haircut véhicule (%)'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='active_contributing_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='membres cotisants actifs'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='activity_comment',
            field=models.TextField(blank=True, verbose_name='commentaire activité annexe'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='activity_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='charges activité annexe'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='activity_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='CA / recettes activité annexe'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='collective_contributions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='cotisations périodiques collectées'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='collective_operating_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='charges de fonctionnement collectives'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='collective_other_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='autres recettes collectives'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='collective_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='épargne du groupement'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='group_activity_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='charges activité commune'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='group_activity_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='CA activité commune (si applicable)'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='group_comment',
            field=models.TextField(blank=True, verbose_name='commentaire groupement'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='has_side_activity',
            field=models.BooleanField(default=False, verbose_name='exerce une activité annexe'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='members_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='nombre de membres'),
        ),
        migrations.AddField(
            model_name='financialanalysis',
            name='solidarity_commitment',
            field=models.BooleanField(default=False, verbose_name='engagement de solidarité entre membres'),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='repayment_mechanism',
            field=models.CharField(blank=True, choices=[('DEGRESSIVE', 'Amortissement dégressif'), ('IN_FINE', 'In fine (capital à terme)'), ('BULLET', 'Remboursement unique (bullet)'), ('CONSTANT', 'Échéances constantes (historique)')], max_length=20, verbose_name='mécanisme de remboursement'),
        ),
    ]
