# Generated by Django 5.1.4 on 2026-09-04 14:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0023_fieldvisit_geo_coordinates'),
        ('tenants', '0004_long_term_snapshots_ged_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditInstructionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('collateral_coverage_mode', models.CharField(choices=[('ALERT', 'Alerte uniquement'), ('BLOCK_SUBMIT', 'Bloquer la soumission'), ('BLOCK_APPROVE', "Bloquer l'approbation finale")], default='ALERT', max_length=20, verbose_name='contrôle couverture garanties')),
                ('require_field_visit', models.BooleanField(default=False, verbose_name='visite terrain obligatoire avant soumission')),
                ('allow_unfavorable_analysis_submit', models.BooleanField(default=True, verbose_name='autoriser la soumission si analyse défavorable')),
                ('require_product_checklist', models.BooleanField(default=False, verbose_name='exiger les pièces obligatoires du produit')),
                ('match_product_client_type', models.BooleanField(default=False, verbose_name='contrôler la cohérence type client / produit')),
                ('kyc_gate', models.CharField(choices=[('ON_SUBMIT', 'À la soumission uniquement'), ('ON_CREATE', 'Dès la création du dossier')], default='ON_SUBMIT', max_length=20, verbose_name='exigence KYC')),
                ('product_bounds_gate', models.CharField(choices=[('ON_SUBMIT', 'À la soumission uniquement'), ('ON_SAVE', 'À chaque enregistrement')], default='ON_SUBMIT', max_length=20, verbose_name='contrôle bornes produit (montant / durée)')),
                ('amount_approved_mode', models.CharField(choices=[('ALLOW', "Saisissable dès l'instruction"), ('FORBID', 'Uniquement à la décision du circuit')], default='ALLOW', max_length=20, verbose_name='saisie du montant approuvé')),
                ('show_readiness_checklist', models.BooleanField(default=True, verbose_name='afficher la checklist de readiness avant soumission')),
                ('enable_cancel_status', models.BooleanField(default=False, verbose_name="autoriser l'annulation formelle du dossier (CANCELLED)")),
                ('allow_collateral_during_approval', models.BooleanField(default=False, verbose_name='autoriser le rattachement de garanties pendant le circuit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='filiale')),
            ],
            options={
                'verbose_name': "politique d'instruction crédit",
                'verbose_name_plural': "politiques d'instruction crédit",
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='unique_credit_instruction_policy_per_tenant')],
            },
        ),
    ]
