# Generated by Django 5.1.4 on 2026-09-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0024_credit_instruction_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='cbs_contract_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='n° contrat CBS (numContrat)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='cbs_demande_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='n° demande CBS (numDemande)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='cbs_demande_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='réf. demande CBS (refDemande)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='cbs_disbursement_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='dernier payload CBS décaissement'),
        ),
        migrations.AddField(
            model_name='loan',
            name='cbs_disbursement_status',
            field=models.CharField(blank=True, default='', help_text='SUBMITTED / CONFIRMED / FAILED / … (callbacks Perfect).', max_length=40, verbose_name='statut décaissement CBS'),
        ),
        migrations.AddField(
            model_name='loan',
            name='cbs_external_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='identifiant externe CBS (externalId)'),
        ),
    ]
