# Generated by Django 5.1.4 on 2026-09-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0025_cbs_disbursement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='currency',
            field=models.CharField(default='XOF', help_text='Code du référentiel Currency (ex. XOF).', max_length=8, verbose_name='devise'),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='periodicity',
            field=models.CharField(default='MONTHLY', help_text='Code du référentiel LoanPeriodicity (ex. MONTHLY).', max_length=32, verbose_name='périodicité'),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='repayment_mechanism',
            field=models.CharField(blank=True, help_text='Code du référentiel RepaymentMethod (ex. DEGRESSIVE).', max_length=32, verbose_name='mécanisme de remboursement'),
        ),
    ]
