# Generated by Django 5.1.4 on 2026-09-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0026_cbs_referentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditinstructionpolicy',
            name='require_surety_signed_contracts',
            field=models.BooleanField(default=True, help_text='Si le dossier a des engagements de caution actifs, chaque caution doit avoir un contrat SURETY généré et signé avant décaissement.', verbose_name='exiger un contrat de cautionnement signé avant décaissement'),
        ),
    ]
